# Generated by Django 2.2.16 on 2022-12-02 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20221201_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipetags',
            options={'verbose_name': 'Тэг рецепта', 'verbose_name_plural': 'Тэги рецепта'},
        ),
        migrations.AlterField(
            model_name='favorites',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.Recipes'),
        ),
        migrations.AlterField(
            model_name='shoplists',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.Recipes'),
        ),
    ]
