# Generated by Django 2.2.16 on 2022-12-08 22:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_auto_20221206_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measuring_unit',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[а-яА-Я_. ]+$')]),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.RegexValidator('^[а-яА-Я ]+$')], verbose_name='Название ингридиента'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='foodgram.Ingredients', verbose_name='ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.RegexValidator('^[а-яА-Я ]+$')], verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[а-яА-Я]+$')]),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$')]),
        ),
    ]
