# Generated by Django 2.2.16 on 2022-12-08 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_auto_20221209_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.RegexValidator('^[а-яА-Я- ]+$')], verbose_name='Название рецепта'),
        ),
    ]
