# Generated by Django 2.2.16 on 2022-11-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_auto_20221126_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='description',
            new_name='text',
        ),
        migrations.AddConstraint(
            model_name='shoplists',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_purchase'),
        ),
    ]
