# Generated by Django 2.2.16 on 2022-11-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_auto_20221129_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название ингридиента'),
        ),
    ]
